### ISSUE TITLE
[Among Us World] Walls colours

### ISSUE THREAD

**Issue by fgonzalezr1998** [RoboTech-URJC/RobotechVirtualChallenge#3]
It is necessary to change the colour of the walls behind both soccer goals because one of them is yellow (the same colour that the other goal) and the other is orange (the same colour than the ball)

**Comment by jginesclavero** [comment]
![image](https://user-images.githubusercontent.com/10533506/95662289-2281bf00-0b36-11eb-9a00-e692341a088a.png)
