### ISSUE TITLE
[ERROR] [1615117217.601467348]: SpawnModel: Failure - model name red_waffle already exist.

### ISSUE THREAD

**Issue by ivrolan** [RoboTech-URJC/RobotechVirtualChallenge#35]
This is the error message I get when launching robots sim_gui.launch and sim.launch.
I think is due to a repetition of the declaration of the models in 
RobotechVirtualChallenge/robots/worlds/robotech_virtual_challenge.world 
and then
RobotechVirtualChallenge/robots/launch/spawn.launch
@P4B5 please take a look to this

**Comment by P4B5** [comment]
Hi @ivrolan!

I just clone the official repo (https://github.com/RoboTech-URJC/RobotechVirtualChallenge) again on my machine to revise this issue following all the instructions and it works well:

1. Check if you clone noetic branch and with --recursive
2. revise dependencies. `rosdep check --from-paths ~/[robotech_ws]/src/RobotechVirtualChallenge -i`
3. check if gazebo plugins package is installed in your machine. `sudo apt-get install ros-noetic-gazebo-plugins`
4. revise .bashrc to check if you configured correctly ros path and TURTLEBOT environment variable
5. launch everything from RobotechVirtualChallenge directory folder not ws or src directories

Cheers!

PS: I've got the same error when I launched gazebo but it the robots appear correctly and the navigation is correct too.

![image](https://user-images.githubusercontent.com/37982892/110239688-7effd380-7f48-11eb-8a16-9330ba2f42fb.png)


![test](https://user-images.githubusercontent.com/37982892/110239886-9f7c5d80-7f49-11eb-9f4a-a07e1fce71d3.gif)

**Comment by P4B5** [comment]
If you made all the steps above try this:

1. check if with `env` if you have the env variable `GAZEBO_MODEL_PATH`
2. if you have remove it
3. launch again gazebo and see if two robots appear
4. If two robots appear launch navigation

Cheers!

**Comment by ivrolan** [comment]
The only dependency that I lack is 
ERROR[robots]: Cannot locate rosdep definition for [rplidar_ros]
	rosdep key : rplidar_ros
	OS name    : ubuntu
	OS version : focal

My .bashrc is:
source /opt/ros/noetic/setup.bash
source ~/catkin_ws/devel/setup.bash
export GAZEBO_MODEL_PATH=$GAZEBO_MODEL_PATH:~/catkin_ws/src/RobotechVirtualChallenge/robots/worlds/models
export TURTLEBOT3_MODEL=waffle
rosdep check --from-paths ~/catkin_ws/src/RobotechVirtualChallenge -i

I have launch the .launch with the GAZEBO_MODEL_PATH and without it. The same error occurs:
After the errors you posted this appears on my terminal:
[red/spawn_urdf-12] process has died [pid 10290, exit code 1, cmd /opt/ros/noetic/lib/gazebo_ros/spawn_model -urdf -model red_waffle -x 2.205 -y 7.0 -z 0.008997 -Y -1.57 -param robot_description __name:=spawn_urdf __log:=/home/ivanlb/.ros/log/7c25cc24-7f42-11eb-a757-7fe9f470a5e0/red-spawn_urdf-12.log].
log file: /home/ivanlb/.ros/log/7c25cc24-7f42-11eb-a757-7fe9f470a5e0/red-spawn_urdf-12*.log
[purple/spawn_urdf-5] process has died [pid 10265, exit code 1, cmd /opt/ros/noetic/lib/gazebo_ros/spawn_model -urdf -model purple_waffle -x 0.205 -y 7.0 -z 0.008997 -Y -1.57 -param robot_description __name:=spawn_urdf __log:=/home/ivanlb/.ros/log/7c25cc24-7f42-11eb-a757-7fe9f470a5e0/purple-spawn_urdf-5.log].
log file: /home/ivanlb/.ros/log/7c25cc24-7f42-11eb-a757-7fe9f470a5e0/purple-spawn_urdf-5*.log
[camera_1/spawn_urdf-18] process has died [pid 10318, exit code 1, cmd /opt/ros/noetic/lib/gazebo_ros/spawn_model -urdf -model single_camera -x 1.0 -y 6.81 -z 6.39 -R -3.14 -P 1.57 -Y 1.57 -param robot_description __name:=spawn_urdf __log:=/home/ivanlb/.ros/log/7c25cc24-7f42-11eb-a757-7fe9f470a5e0/camera_1-spawn_urdf-18.log].
log file: /home/ivanlb/.ros/log/7c25cc24-7f42-11eb-a757-7fe9f470a5e0/camera_1-spawn_urdf-18*.log

I have been searching and found this:
https://answers.ros.org/question/271978/error-while-launching-robot-model/

**Comment by ivrolan** [comment]
I can navigate, the thing is that the models aren't appearing on gazebo
